# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-05 13:44
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EyesColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('rgb_color', colorful.fields.RGBColorField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='HairColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('rgb_color', colorful.fields.RGBColorField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SkinColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('rgb_color', colorful.fields.RGBColorField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='colortype',
            name='eyes_colors',
            field=models.ManyToManyField(to='colortyperecognition.EyesColor'),
        ),
        migrations.AddField(
            model_name='colortype',
            name='hairs_colors',
            field=models.ManyToManyField(to='colortyperecognition.HairColor'),
        ),
        migrations.AddField(
            model_name='colortype',
            name='skins_colors',
            field=models.ManyToManyField(to='colortyperecognition.SkinColor'),
        ),
    ]
