# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-06 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colortyperecognition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('coords_of_eyes', models.TextField()),
                ('coords_of_hair', models.TextField()),
                ('coords_of_face', models.TextField()),
            ],
        ),
    ]
